### PR TITLE
Instance operator: avoid status updates for intermediate operations

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This PR introduces a quick and dirty fix to prevent stopped persistent VMs from hanging in intermediate statuses. Specifically, status updates are no longer performed after completing with success intermediate operations, replaced by simple logs. Oauth2-proxy related tasks are not updated since removed by #490. Status management would still require a complete refactoring to improve the overall workflow. 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Staging environment

### CODE REVIEW

**Review by QcFe — APPROVED** [review]
/lgtm

**Review by GabriFila — APPROVED** [review]

**Pull request merged**
