### PR TITLE
Fix wrong VM instance generation

### PR DESCRIPTION
**Pull request by palexster**
# Description

This PR fixes the memory quantity associated to a VM instance in the instance operator

# How Has This Been Tested?

Unit Tests

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]

**Comment by GabriFila** [comment]
This PR seems ok. I just noticed 2 things:
1. the PR is composed by3 commits with the same name (I believe some changes in some commits are related only to linting). 
2.  the `TestCheckLabels` is ok, but, just to check, I didn't find any place in the instance controller/creation code that adds those kinds of labels (`crownlabs.polito.it/operator-selector`). My point is not related to the test itself since it tests the checking of labels not the adding of a label, but maybe you want to actually add it also to the resources created by the operator and it is not present at the moment

**Comment by palexster** [comment]
> This PR seems ok. I just noticed 2 things:
> 
> 1. the PR is composed by3 commits with the same name (I believe some changes in some commits are related only to linting).

Fixed thanks!

> 2. the `TestCheckLabels` is ok, but, just to check, I didn't find any place in the instance controller/creation code that adds those kinds of labels (`crownlabs.polito.it/operator-selector`). My point is not related to the test itself since it tests the checking of labels not the adding of a label, but maybe you want to actually add it also to the resources created by the operator and it is not present at the moment

The label is not added by the controller itself, and the instance controller just checks if the namespace is eligible. However, I think we should define a cross-operator label strategy and implement it consistently across the different operator. 

I would not include this in the PR, but I am opening an issue about that.

**Review by GabriFila — APPROVED** [review]
Lgtm

**Pull request merged**
