### PR TITLE
Add persistent VMs in UI

### PR DESCRIPTION
**Pull request by GabriFila**
# Description

This PR includes minor changes to add the support for persitent VMs to the UI

### CODE REVIEW

**Review by frisso — APPROVED** [review]

**Comment by frisso** [comment]
That's really nice!
Is there any way to test it in the pre-prod environment? E.g., with a VM image that supports persistency?

**Review by giorio94 — APPROVED** [review]
Thanks @GabriFila!

@frisso Yes, I should have enabled your account to use the pre-production operator and access the test VM -- Ubuntu Desktop (Persistent). The updated dashboard is available at https://425.staging.crownlabs.polito.it

**Review by palexster — APPROVED** [review]

**Comment by frisso** [comment]
@GabriFila @giorio94 Should we merge this PR?

**Comment by GabriFila** [comment]
I noticed a little positioning problem in the message I placed under the instances tab. I would like to place it under both tabs in case the width allows for the abs to be adjacent.

I'll try to fix it today

**Pull request merged**
