### PR TITLE
GitHub actions pipelines: staging environment

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This PR updates and completes the GitHub actions pipelines to deploy/undeploy the staging environment (i.e. the one used to test the modifications of a new PR before being merged to master).

Specifically:
* A deploy/update is triggered by a `/deploy-staging` comment from a collaborator with write access to CrownLabs. It triggers the push of the images to DockerHub and an event in CrownOps to perform the actual deployment. The outcome is reported through a comment, which displays the information to access the environment. The choice regarding the usage of comments is to prevent the deployment when not necessary (e.g. modifying unrelated components) and to support forks. 
* An undeploy is triggered by a `/undeploy-staging` comment from a collaborator with write access to CrownLabs or by the PR being merged/closed. It triggers an event in CrownOps to delete the staging resources.  

As for now, new staging deployments trigger the issuance of a new digital certificate. Although this is currently not a problem since we are way below the Let's Encrypt limitations, in case of problems it may be necessary to consider the usage of a wildcard certificate. 

As for the names of the slash commands, I couldn't come up with any better names. Suggestions are obviously welcome.

### CODE REVIEW

**Review by frisso — APPROVED** [review]
This looks very very very useful.

**Comment by giorio94** [comment]
/merge

This is just a test. No merge is expected to occur

**Review by palexster — APPROVED** [review]

**Pull request merged**
