### PR TITLE
qlkube: parametrize exposed and subscription-enabled APIs

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This PR introduces the possibility to parametrize through helm the set of APIs exposed through graphql and the ones for which subscriptions are enabled.

# How Has This Been Tested?

- [x] Staging environment

### CODE REVIEW

**Review by QcFe — DISMISSED** [review]
/lgtm

**Comment by QcFe** [comment]
Are we waiting for the other qlkube PR to be merged prior to testing this one?

**Comment by giorio94** [comment]
> Are we waiting for the other qlkube PR to be merged prior to testing this one?

Yep, otherwise it would be crashing.

**Review by QcFe — APPROVED** [review]
Looks good

**Review by GabriFila — APPROVED** [review]

**Pull request merged**
