### PR TITLE
Harbor documentation: fix dead link

### PR DESCRIPTION
**Pull request by air-31**
# Description

This PR fixes a dead link present in the Harbor (docker registry) documentation.

### CODE REVIEW

**Review by cheina97 — APPROVED** [review]

**Review by frisso — APPROVED** [review]
Is there any reasons we're using link to version 2.7.0, which is not thd latest?

**Comment by air-31** [comment]
Yes, the reason is the absence of the corresponding page in the latest version documentation

**Comment by QcFe** [comment]
@frisso guess when I updated it that was the latest available version...
It seems the 2.8 release has been published just 3 weeks ago :)

**Pull request merged**
