### PR TITLE
instance-controller: remove oauth2-proxy creation

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This PR removes the creation of the oauth2-proxy objects from the instance operator. It assumes the existence of a centralized oauth2-proxy deployment and configures the appropriate ingress annotations based on the URL specified as input parameter.
Finally, it removes a set of CORS-related annotation which appear to be no longer required.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Unit tests
- [x] Staging environment

### CODE REVIEW

**Review by frisso — APPROVED** [review]

**Comment by frisso** [comment]
Just to know, does this require some changes to the documentation as well?
E.g., something here? https://github.com/netgroup-polito/CrownLabs/tree/master/infrastructure/identity-provider#accessing-k8s-cluster-using-keycloak-as-authentication-server

**Comment by giorio94** [comment]
> Just to know, does this require some changes to the documentation as well?
> E.g., something here? https://github.com/netgroup-polito/CrownLabs/tree/master/infrastructure/identity-provider#accessing-k8s-cluster-using-keycloak-as-authentication-server

No, this is related only to the authentication in front of the user instances, and it is completely transparent from the users' point of view. Overall, this change is required in view of the authentication for the new dashboard. Still, I was wondering whether to take the chance to completely change this approach, to reduce the number of object created for each new VM and save resources in the cluster.

**Comment by frisso** [comment]
For me, any improvement is welcome.
The only limit, as usual, is the manpower required to achieve the above objective, given the high amount of work that we're already carrying on.

**Comment by QcFe** [comment]
Does it make sense to test this one again?

**Comment by giorio94** [comment]
> Does it make sense to test this one again?

Definitely

**Comment by QcFe** [comment]
I fear there's some issue with `websiteBaseUrl` instead of `websiteBaseUri` and the deployment of the operator

**Comment by giorio94** [comment]
> I fear there's some issue with `websiteBaseUrl` instead of `websiteBaseUri` and the deployment of the operator

That was expected, since the inventories in CrownOps are still old. I changed that URI to URL for consistency (though I probably named that so). And the new flag is not configured at all.

**Review by GabriFila — APPROVED** [review]

**Pull request merged**
