### PR TITLE
Clock fix

### PR DESCRIPTION
**Pull request by cannarelladev**
# Description

Just a minor fix on the CL App Clock, during instance creation there was usually a visual glitch that showed a negative AGE

### CODE REVIEW

**Comment by giorio94** [comment]
Just a minor note. It is not guaranteed client and server timers are synchronized. Would make sure negative values are shown as `now` to prevent glitches in case of clock skews.

**Comment by cannarelladev** [comment]
@giorio94 dome

**Comment by cannarelladev** [comment]
> Just a minor note. It is not guaranteed client and server timers are synchronized. Would make sure negative values are shown as `now` to prevent glitches in case of clock skews.

@giorio94 Done!

**Pull request merged**
