### PR TITLE
Modal Alert: decorator

### PR DESCRIPTION
**Pull request by cheina97**
Add a decorator for the ModalAlert's component storybook.

### CODE REVIEW

**Review by GabriFila — APPROVED** [review]

**Comment by QcFe** [comment]
Controls of the storybook do not seem functional anymore...
(The following are just a maniac's obsession, but since you're at this file already I'd kindly ask you to remove the space before the "..."s since it's typographically weird to be seen, at least for me 🥴)

**Comment by QcFe** [comment]
Is it normal that the close button of the modal doesn't work anymore?

**Comment by cheina97** [comment]
> Is it normal that the close button of the modal doesn't work anymore?

Yes, the last 2 commits represent 2 different version, the last one use a cotrol not a state

**Review by QcFe — APPROVED** [review]

**Pull request merged**
