### PR TITLE
Infrastructure: add oauth2-proxy installation docs

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This PR adds the documentation regarding the installation of the centralized oauth2-proxy deployment, which is used to prevent access to the graphical desktop of the user instances to unauthenticated users. Related to #490 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Performing the deployment of oath2-proxy in the cluster

### CODE REVIEW

**Review by QcFe — APPROVED** [review]
Looks good to me. Was just thinking if it's the case "generalize" the crownlabs domains with the usual example.com

**Comment by giorio94** [comment]
> Looks good to me. Was just thinking if it's the case "generalize" the crownlabs domains with the usual example.com

That is something we have never been really that consistent throughout the repo. Still, as for the infrastructural manifests we usually kept the correct domain, to make them as similar as possible to the actual ones. Would keep so for the moment, since the URLs are anyhow public in the end. Differently, I personally prefer the *fake* ones inside the Helm charts, to make it more evident we are using the values from CrownOps.

**Review by GabriFila — APPROVED** [review]

**Comment by QcFe** [comment]
\rebase

**Pull request merged**
