### PR TITLE
Dashboard Update

### PR DESCRIPTION
**Pull request by nappozord**
# Description

This PR updates the dashboard to the latest version. Also fixes a bug where sometimes the tenant would not be registered, causing the dashboard to not look for related images and instances (an so make it look like the two lists are loading indefinitely).

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]

**Comment by giorio94** [comment]
/hold

The dashboard version deployed in the staging environment has some problems

**Review by frisso — APPROVED** [review]

**Pull request merged**
