### PR TITLE
Instance Operator: status management refactoring

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This commit starts the refactoring of the instance operator, migrating to a more Kubernetes-native method to handle the status update. Additionally, it starts the migration to more structured logging.

Ref: #512 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Unit testing
- [x] Deploy staging

### CODE REVIEW

**Review by QcFe — APPROVED** [review]
Looks alright, I hope I haven't missed too many things... 🥴

**Review by palexster — APPROVED** [review]

**Pull request merged**
