### PR TITLE
Initial version of the helm chart

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This PR introduces an initial version of an helm chart to automate the deployment of CrownLabs. 
At the moment, it manages the following components:
* instance-operator
* tenant-operator
* dashboard

Tested verifying the correct deployment of both the production and the pre-production environment

### CODE REVIEW

**Review by palexster — APPROVED** [review]

**Comment by giorio94** [comment]
/hold 

Waiting for a bit more testing, to directly include possible bug fixes

**Review by alacuku — APPROVED** [review]
/lgtm

**Pull request merged**
